language: csharp
solution: Algebra.sln
install:
- nuget restore Algebra.sln
- nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
- xbuild /p:Configuration=Release Algebra.sln
- mono testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe Tests/bin/Release/Tests.dll
